server:
  port: 8085

#person: #对象
#  lastName: zhangsan
#  age: 18
#  boss: false
#  birth: 2019/12/01
#  maps: {k1: v1,k2: 12} #map
#  lists: #list
#    - lisi
#    - zhaoliu
#  dog:  #对象
#    name: xiaogou
#    age: 2